name: demo

on:
  push:
    branches:
      - test-dev
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'

jobs:
  demo:
    runs-on: test-dev
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: print node version
        run: |
          node -v 
          npm -v
          echo 'hello github actions'
  test2:
    runs-on: test-dev
    steps:
      - run: touch a.txt
      - run: echo 100 > a.txt
      - run: cat a.txt
